mongodb:
  replicaCount: 1
  image: mongo
  tag: latest
  dbUser: mongo
  dbPassword: mongo123
  dbName: test

nestjs:
  image: leanespind92/desafio12
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000  # Asegúrate de que este puerto esté correctamente asignado

serviceAccount:
  create: true
  name: ""  # Deja esto vacío para auto-generar un nombre

service:
  type: LoadBalancer  # Cambia a ClusterIP si no necesitas LoadBalancer
  port: 80  # Asegúrate de que esto coincida con lo que tu aplicación necesita

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: "chart-example.local"
      paths: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

env:
  MONGO_DB_URI: "mongodb://mongo:mongo123@mongodb-service:27017/test"
  MONGO_DB_NAME: "test"
  MONGO_DB_USER: "mongo"
  MONGO_DB_PASS: "mongo123"
