apiVersion: v1
kind: Service
metadata:
  name: nestjs-service  # Nombre del servicio
  namespace: <tu-namespace>  # Asegúrate de que coincida con el namespace de tu deployment
  labels:
    helm.sh/chart: nestjs-app-0.1.0
    app.kubernetes.io/name: nestjs-app  # Nombre de la aplicación
    app.kubernetes.io/instance: nestjs-app
    app.kubernetes.io/part-of: nestjs-app
spec:
  type: {{ .Values.service.type }}  # Tipo de servicio, definido en values.yaml
  ports:
    - port: {{ .Values.service.port }}  # Usar el puerto definido en values.yaml
      targetPort: {{ .Values.nestjs.port }}  # Asegúrate de que coincida con el puerto de tu contenedor
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: nestjs-app  # Debe coincidir con el deployment
